import { arraySidebar } from "vuepress-theme-hope";

export const devops = arraySidebar([
    {
        text: "Linux",
        icon: "/linux-brands.svg",
        prefix: "00-linux/",
        collapsible: true,
        children: [
            "1-linux-ssh-key.md",
            "2-big-file-split.md",
            "3-inotify.md",
            "4-unlock-user-login.md",
            "20231220-default-home-after-login.md",
            "20231223-modify-sudo-configuration.md",
            "signal.md",
        ],
    },{
        text: "Shell",
        icon: "/terminal-solid.svg",
        prefix: "01-shell/",
        collapsible: true,
        children: [
            "00shell-basics-foundations.md",
        ],
    },{
        text: "Docker",
        icon: "/docker-brands.svg",
        prefix: "02-docker/",
        collapsible: true,
        children: [
            "2023110400-docker-basic-knowledge-common-commands.md",
            "2023110401-docker-basic-knowledge-configuration-files.md",
            "2023110402-docker-basic-knowledge-dockerfile.md",
            "2023110403-docker-basic-knowledge-docker-network.md",
            "2023120400-docker-advanced-knowledge-hot-update.md",
            "2024032100-docker-advanced-knowledge-docker-logs.md",
            "2024041000-docker-basic-knowledge-delete-images.md",
            "2024041000-docker-advanced-knowledge-clean-docker-data.md",
            "2024050300-docker-advanced-knowledge-docker-image-sync-skopeo.md",
            "2024050310-docker-advanced-knowledge-skopeo-command-details.md",
            "2024050510-docker-advanced-knowledge-dive-command-details.md",
            "2024052500-docker-advanced-knowledge-remote-docker.md",
            "docker99-colima.md",
            "docker01-container-essence.md",
            "docker02-unionfs.md",
            "docker03-enter-container.md",
            "docker04-namespace.md",
            "docker05-cgroups.md",
            "docker06-vm-and-container-tech.md",
            "docker07-kill-container-pid1.md",
            "docker08-zombie-container-process.md",
            "docker09-container-issues.md",
            "docker-usually-error.md",
        ],
    },
    {
        text: "K8s",
        icon: "/k8s.svg",
        prefix: "03-k8s/",
        collapsible: true,
        children: [
            "2023110400_Kubernetes-cluster-management-tool-kubectl.md",
            "2023110401_Kubernetes-cluster-YAML-file-details.md",
            "2023110402_Kubernetes-core-technology-Pod.md",
            "2023110403_Kubernetes-core-technology-Controller.md",
            "2023110404_Kubernetes-core-technology-Service.md",
            "2023110405_Kubernetes-controller-Controller-details.md",
            "2023110406_Kubernetes-configuration-management.md",
            "2023110406_Kubernetes-cluster-security-mechanism.md",
            "2023110407_Kubernetes-core-technology-Ingress.md",
            "2023110408_Kubernetes-core-technology-Helm.md",
            "2023110409_Kubernetes-persistent-storage.md",
            "2023110410_Kubernetes-cluster-resource-monitoring.md",
            "2023110411_Kubernetes-build-high-availability-cluster.md",
            "2024050300_Kubernetes-controller-job.md",
            "2024050301_Kubernetes-controller-cronjob.md",
            "2023072001-K8s-advanced-operation-resource-list.md",
            "2023072002-K8s-advanced-operation-pod-security-policy.md",
            "2023072003-K8s-advanced-operation-limit-namespace-resources.md",
            "2023072004-K8s-advanced-operation-k8sCommand.md",
            "2023072000-k8s-advanced-operation-deploy-rollbacks.md",
            "2023071900-K8s-operations-unable-to-validate-against-any-pod-security-policy.md",
            "2023071900-K8s-operations-get-pod-last-exit-reason.md",
            "2023071901-K8s-operations-k8s-output-jsonpath.md",
            "2023071902-k8s-operations-kindnotset.md",
            "2023071903-k8s-operations-nginx-controller-expose-ports.md",
            "2023071904-k8s-operations-yaml-format-issues.md",
        ],
    },
    {
        text: "Nexus",
        icon: "/Logo_of_Sonatype_Nexus_Repository.svg.png",
        prefix: "05-nexus/",
        collapsible: true,
        children: [
            "02-nexus-upload-frontend-dependencies.md",
            "03-nexus-upload-java-dependencies.md",
            "04-download-upload-frontend-dependencies-npm.md",
            "05-download-frontend-dependencies-yarn-resoluted.md",
            "06-download-frontend-dependencies-yarn-resolution.md",
            "07-download-frontend-dependencies-pnpm.md",
            "08-frontend-dependencies-overview.md",
            "09-download-go-dependencies.md",
            "10-frontend-intranet-modification.md",
            "11-migrate-nexus-dependencies.md",
            "12-download-aliyun-maven-repo-dependencies.md",
            "13-download-python-dependencies.md",
            "14-upload-python-dependencies.md",
            "15-manual-upload-frontend-dependencies.md",
            "16-deploy-jar-to-nexus.md",
            "17-lanaguage-depen-url.md",
        ],
    },
    {
        text: "Jenkins",
        icon: "/jenkins-brands.svg",
        prefix: "07-jenkins/",
        collapsible: true,
        children: [
            "000-Jenkins-deploy.md",
            "101-jenkins-https-domain.md",
            "0001-jenkins-plugin.md",
            "002-jenkins-shard-library.md",
            "003-jenkins-agent.md",
            "004-jenkins-command-root.md",
            "200-jenkins-common-issues.md",
            "201-jenkins-ssh-high-version-connect-issue.md",
        ],
    },
    {
        text: "Ansible",
        icon: "/ansible.svg",
        prefix: "04-ansible/",
        collapsible: true,
        children: [
            "00-base.md",
            "01-command.md",
            "02-modules.md",
            "03-playbook.md",
            "04-template.md",
            "05-role.md",
            "90-ansible-operator.md",
        ],
    },
    {
        text: "Helm",
        icon: "/helm-svgrepo-com.svg",
        prefix: "06-helm/",
        collapsible: true,
        children: [
            "000-helm-install.md",
            "001-helm-init.md",
            "002-helm-grammer.md",
            "003-helm-usage.md",
        ],
    },
    {
        text: "Minio",
        icon: "/minio.svg",
        prefix: "08-minio/",
        collapsible: true,
        children: [
            "00-minio-mc-command.md",
        ],
    },
    {
        text: "Mysql",
        icon: "/database-solid.svg",
        prefix: "09-mysql/",
        collapsible: true,
        children: [
            "00-enable-bin-log.md",
        ],
    },
    {
        text: "镜像仓库",
        icon: "/registry.png",
        prefix: "14-registry/",
        collapsible: true,
        children: [
            "1-registry.md",
            "2-registry-https-domain.md",
        ],
    }
]);