import { arraySidebar } from "vuepress-theme-hope";

export const language = arraySidebar([
    {
        text: "JAVA语言",
        icon: "/java-brands.svg",
        prefix: "00-java/",
        collapsible: true,
        children: [
            {
                text: "JVM",
                prefix: "JVM/",
                collapsible: true,
                children: [
                    "1_JVM与Java体系结构.md",
                    "2_类加载子系统.md",
                    "3_运行时数据区概述及线程.md",
                    "4_程序计数器.md",
                    "5_虚拟机栈.md",
                    "6_本地方法接口.md",
                    "7_本地方法栈.md",
                    "8_堆.md",
                    "9_方法区.md",
                    "10_对象实例化内存布局与访问定位.md",
                    "11_直接内存.md",
                    "12_执行引擎.md",
                    "13_StringTable.md",
                    "14_垃圾回收概述.md",
                    "15_垃圾回收相关算法.md",
                    "16_垃圾回收相关概念.md",
                    "17_垃圾回收器.md",
                    "221_Class文件结构.md",
                    "222_字节码指令集与解析举例.md",
                    "223_类的加载过程详解.md",
                    "224_再谈类的加载器.md",
                    "2024052400-java-jvm.md",
                    "2024052410-java-jvm-command.md",
                    "2024052500-java-jvm-jstack.md",
                    "2024052520-java-jvm-jstack-dump.md",
                    "2024052530-java-jvm-jstack-state.md",
                    "2024052800-java-jvm-javac-javap.md",
                ]
            },
            {
                text: "并发编程",
                prefix: "JUC/",
                collapsible: true,
                children: [
                    "2024052600-juc-system-pv.md",
                ],
            },
        ],
    },
    {
        text: "前端",
        icon: "/npm-brands.svg",
        prefix: "01-fronted/",
        collapsible: false,
        children: [
            "00-打补丁解决前端bug.md",
            "02-nvm切换版本不生效.md",
            "03-vuepres-theme-hope报错.md",
            "04-local-run-hoppscotch.md",
        ],
    },
    {
        text: "Nginx",
        icon: "/icons8-nginx.svg",
        prefix: "02-nginx/",
        collapsible: false,
        children: [
            "00-nginx-https.md",
            "01-https-encode-process.md",
        ],
    },
    {
        text: "Mysql",
        icon: "/database-solid.svg",
        prefix: "05-mysql/",
        collapsible: false,
        children: [
            "01-基础查询.md",
            "02-函数.md",
            "03-复杂查询.md",
            "04-进阶查询.md",
            "05-连接查询.md",
            "06-mysql-dml.md",
            "101-mysql-how-to-execute-select-sql.md",
            "102-mysql-how-to-execute-update-sql.md",
            "103-transanction.md",
            "104-index.md",
            "20241008-mysql-errors.md",
        ],
    },
    {
        text: "Redis",
        icon: "/registered-solid.svg",
        prefix: "06-redis/",
        collapsible: false,
        children: [
            "base-structure.md",
            "complex-structure.md",
            "redis-base.md",
            "persistence.md",
            "cache-strategy.md",
            "redis-lock-reason.md",
            "redis-memory-manage.md"
        ],
    },
]);