import { arraySidebar } from "vuepress-theme-hope";

export const language = arraySidebar([
    {
        text: "JAVA语言",
        icon: "/java-brands.svg",
        prefix: "00-java/",
        collapsible: true,
        children: [
            {
                text: "JVM",
                prefix: "JVM/",
                collapsible: true,
                children: [
                    "1_JVM-and-Java-architecture.md",
                    "2_class-loading-subsystem.md",
                    "3_runtime-data-areas-thread.md",
                    "4_program-counter.md",
                    "5_virtual-machine-stack.md",
                    "6_native-method-interface.md",
                    "7_native-method-stack.md",
                    "8_heap.md",
                    "9_method-area.md",
                    "10_object-instantiation-memory-layout.md",
                    "11_direct-memory.md",
                    "12_execution-engine.md",
                    "13_StringTable.md",
                    "14_garbage-collection-overview.md",
                    "15_garbage-collection-algorithms.md",
                    "16_garbage-collection-concepts.md",
                    "17_garbage-collectors.md",
                    "221_Class-file-structure.md",
                    "222_bytecode-instruction-set-examples.md",
                    "223_class-loading-process-details.md",
                    "224_class-loaders-discussion.md",
                    "2024052400-java-jvm.md",
                    "2024052410-java-jvm-command.md",
                    "2024052500-java-jvm-jstack.md",
                    "2024052520-java-jvm-jstack-dump.md",
                    "2024052530-java-jvm-jstack-state.md",
                    "2024052800-java-jvm-javac-javap.md",
                ]
            },
            {
                text: "并发编程",
                prefix: "JUC/",
                collapsible: true,
                children: [
                    "3-thread-pool.md",
                    "2024052600-juc-system-pv.md",
                ],
            },
        ],
    },
    {
        text: "前端",
        icon: "/npm-brands.svg",
        prefix: "01-fronted/",
        collapsible: false,
        children: [
            "00-patch-fix-frontend-bug.md",
            "02-nvm-switch-version-not-effective.md",
            "03-vuepress-theme-hope-error.md",
            "04-local-run-hoppscotch.md",
        ],
    },
    {
        text: "Nginx",
        icon: "/icons8-nginx.svg",
        prefix: "02-nginx/",
        collapsible: false,
        children: [
            "00-nginx-https.md",
            "01-https-encode-process.md",
        ],
    },
    {
        text: "Mysql",
        icon: "/database-solid.svg",
        prefix: "05-mysql/",
        collapsible: false,
        children: [
            "01-basic-queries.md",
            "02-functions.md",
            "03-complex-queries.md",
            "04-advanced-queries.md",
            "05-join-queries.md",
            "06-mysql-dml.md",
            "101-mysql-how-to-execute-select-sql.md",
            "102-mysql-how-to-execute-update-sql.md",
            "103-transanction.md",
            "104-index.md",
            "106-mysql-execuation-plan.md",
            "107-mysql-engines.md",
            "20241008-mysql-errors.md",
        ],
    },
    {
        text: "Redis",
        icon: "/registered-solid.svg",
        prefix: "06-redis/",
        collapsible: false,
        children: [
            "base-structure.md",
            "complex-structure.md",
            "redis-base.md",
            "persistence.md",
            "cache-strategy.md",
            "redis-lock-reason.md",
            "redis-memory-manage.md",
            "redis-cluster.md",
            "redis-sentinel.md"
        ],
    },
]);