import { arraySidebar } from "vuepress-theme-hope";

export const language = arraySidebar([
    {
        text: "JAVA语言",
        icon: "/java-brands.svg",
        prefix: "00-java/",
        collapsible: true,
        children: [
            "JUC/2024052600-juc-system-pv.md",
            "JVM/1_JVM与Java体系结构.md",
            "JVM/2_类加载子系统.md",
            "JVM/3_运行时数据区概述及线程.md",
            "JVM/4_程序计数器.md",
            "JVM/5_虚拟机栈.md",
            "JVM/6_本地方法接口.md",
            "JVM/7_本地方法栈.md",
            "JVM/8_堆.md",
            "JVM/9_方法区.md",
            "JVM/10_对象实例化内存布局与访问定位.md",
            "JVM/11_直接内存.md",
            "JVM/12_执行引擎.md",
            "JVM/13_StringTable.md",
            "JVM/14_垃圾回收概述.md",
            "JVM/15_垃圾回收相关算法.md",
            "JVM/16_垃圾回收相关概念.md",
            "JVM/17_垃圾回收器.md",
            "JVM/221_Class文件结构.md",
            "JVM/222_字节码指令集与解析举例.md",
            "JVM/223_类的加载过程详解.md",
            "JVM/224_再谈类的加载器.md",
            "JVM/2024052400-java-jvm.md",
            "JVM/2024052410-java-jvm-command.md",
            "JVM/2024052500-java-jvm-jstack.md",
            "JVM/2024052520-java-jvm-jstack-dump.md",
            "JVM/2024052530-java-jvm-jstack-state.md",
            "JVM/2024052800-java-jvm-javac-javap.md",
        ],
    },
    {
        text: "前端",
        icon: "/npm-brands.svg",
        prefix: "01-fronted/",
        collapsible: false,
        children: [
            "00-打补丁解决前端bug.md",
            "02-nvm切换版本不生效.md",
            "03-vuepres-theme-hope报错.md",
            "04-local-run-hoppscotch.md",
        ],
    },
    {
        text: "Nginx",
        icon: "/icons8-nginx.svg",
        prefix: "02-nginx/",
        collapsible: false,
        children: [
            "00-nginx-https.md",
            "01-https-encode-process.md",
        ],
    },
    {
        text: "Mysql",
        icon: "/database-solid.svg",
        prefix: "05-mysql/",
        collapsible: false,
        children: [
            "01_基础查询.md",
            "02-函数.md",
            "03-复杂查询.md",
            "04-进阶查询.md",
            "05-连接查询.md",
            "06-DML语句.md",
            "101-查询语句如何执行.md",
            "102-更新语句是如何执行的.md",
            "103-事务.md",
            "20231022-索引.md",
            "20241008-mysql-errors.md",
        ],
    },
    {
        text: "Redis",
        icon: "/registered-solid.svg",
        prefix: "06-redis/",
        collapsible: false,
        children: [
            "base-structure.md",
            "persistence.md",
        ],
    },
]);